### ISSUE TITLE
License hard to spot

### ISSUE THREAD

**Issue by maribu** [litex-hub/pythondata-cpu-naxriscv#5]
Hi,

according to `setup.py` this is licensed under MIT. Is that correct?

It would be nice if it would be easier to figure out what license applies to the repo. Thx!

**Comment by Dolu1990** [comment]
Hi,

NaxRiscv itself is MIT.

@enjoy-digital Sound good that i add the MIT license to this repo ?

**Comment by enjoy-digital** [comment]
@Dolu1990: Sure!
